#pragma once

#define CFG_STORAGE "C:/Users/Razmik/Desktop/storage/%u/"
#define CFG_CALIBRATION_FILE "C:/Users/Razmik/Desktop/storage/standard.calib"

#define CFG_IMAGE_EXTENTION ".png"
#define CFG_CAPTURE_INTERVAL 1000
#define CFG_BOARD_W 8
#define CFG_BOARD_H 6
#define CFG_BOARD_CELL_SIZE 72
#define CFG_INT_DEFAULT_CAPTURE_COUNT 15
#define CFG_EXT_DEFAULT_CAPTURE_COUNT 1
#define CFG_TRACKING_SERVER_IP "169.254.162.157"

enum NI_CALIBRATION_TYPE{
	NI_CALIBRATION_TYPE_INTRINSIC_EXTRINSIC = '1', 
	NI_CALIBRATION_TYPE_INTRINSIC = '2',
	NI_CALIBRATION_TYPE_EXTRINSIC = '3', 
	NI_CALIBRATION_TYPE_DEPTH = '4',
	NI_CALIBRATION_TYPE_PAIR = '5'
};

enum  NI_SENSOR_TYPE{
	NI_SENSOR_TYPE_RGB = 'c',
	NI_SENSOR_TYPE_IR = 'i'
};